version: '3.3'

services:
  database:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  pg_data:
